server:
  port: 50000

ibspay:
  url: http://localhost:40000
  access-key: test
  access-secret: test
  payment-notify-url: http://localhost:${server.port}/notification/payment
  refund-notify-url: http://localhost:${server.port}/notification/refund
